config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :users #only: [:new, :create, :show]

  resources :galleries, only: [:new, :create, :show]

  # Create a better looking URL for logging in
  resources :sessions, only: [:new, :create, :destroy]
  get 'sessions/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  get '/home', to: 'users#home'
  get '/galleries/:id', to: 'galleries#show'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :gallery
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :user
  has_many :events

  belongs_to :rep, class_name: "User", foreign_key: "user_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  # has_and_belongs_to_many :favorites, class_name: "Gallery"

  has_one :gallery # that they rep, if they are reps

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 6..20}
  validates :zip_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

     # Make the current_user method available to views, not just controllers!
    helper_method :current_user, :rep

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
      redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
    end

    def rep
      current_user.gallery_rep
    end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def new
    @gallery = Gallery.new
    @gallery.rep = current_user
  end

  def show
    @gallery = current_user.gallery
  end


  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.user = current_user
    if @gallery.save
      render 'users/home'
    else
      render :new
    end
  end

  private
    # Implement Strong Params
    def gallery_params
      params.require(:gallery).permit(:name, :street_address, :city, :state, :zip_code, :website, :genres, :days_open, :hours_open, :img_uri, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/home'
    else
      flash.now.alert = 'Forget your login info? - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:home]

  def profile

  end

  def home
      @gallery = current_user.gallery
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    if @user.id = nil
      redirect_to root_path, notice: "You have to sign in!"
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      if params["user"]["gallery_rep"] == "1"
        redirect_to new_gallery_path
      else
        redirect_to '/home'
      end
    else
      render :new
    end
  end

  #def profile_build
   # redirect_to users_profile_path

  #end

  def new_gallery_rep
    @user = User.find(params[:id])
    render "new_gallery_rep"
  end

  private
    # Implement Strong Params
    def user_params
      params.require(:user).permit(:name, :email, :zip_code, :password, :password_confirmation, :gallery_rep)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galleries/new.html.erb
<main id="profile">
<%= form_for @gallery do |f| %>
  <% if @gallery.errors.any? %>
    <div class="error_messages">
      <h2>Need more info to get you set up!</h2>
      <ul>
        <% for message in @gallery.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <form class="form-horizontal" role="form">
        <fieldset>

          <!-- Form Name -->
          <legend>Set Up Gallery Profile</legend>

          <div class="form-group">
            <%= f.label :name, "Gallery Name", class: "col-sm-10 control-label" %>
              <div class="col-sm-12">
                <%= f.text_field :name, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :street_address, class: "col-sm-10 control-label" %>
              <div class="col-sm-12">
                <%= f.text_field :street_address, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :city, class: "col-sm-10 control-label" %>
              <div class="col-sm-12">
                <%= f.text_field :city, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :state, class: "col-sm-10 control-label" %>
              <div class="col-sm-12">
                <%= f.text_field :state, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :zip_code, "Primary Area (Zip-Code)", class: "col-sm-10 control-label" %>
              <div class="col-sm-12">
                <%= f.text_field :zip_code, value: current_user.zip_code, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :website, "Website Link (if applicable)", class: "col-sm-10 control-label" %>
              <div class="col-sm-12">
                <%= f.text_field :website, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :genres, "Genres Supported (List)", class: "col-sm-10 control-label" %>
              <div class="col-sm-12">
                <%= f.text_field :genres, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :days_open, "Days Open for Visitors", class: "col-sm-10 control-label" %>
              <div class="col-sm-12">
                <%= f.text_field :days_open, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :hours_open, "Business Hours", class: "col-sm-10 control-label" %>
              <div class="col-sm-12">
                <%= f.text_field :hours_open, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :img_uri, "Profile Image URI", class: "col-sm-10 control-label" %>
              <div class="col-sm-12">
                <%= f.text_field :img_uri, class: "form-control" %>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="pull-right">
                <%= f.submit "Submit Profile!", class: "btn btn-primary" %>
                <!--<button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-primary">Save</button> -->
              </div>
            </div>
          </div>

        </fieldset>
      </form>
    </div><!-- /.col-lg-12 -->
  </div><!-- /.row -->


<% end %>
</main>

app/views/galleries/show.html.erb
<div class="container" style="margin-top: 20px; margin-bottom: 20px;">
  <div class="row panel">
    <div class="col-md-4" style="height: 300px; background-size: cover; background-image:url('<%= current_user.gallery.img_uri %>');">
          <a href="#" class="follow_btn hidden-xs">Follow</a>
    </div>
        <div class="col-md-8  col-xs-12">
           <img src="http://lorempixel.com/output/people-q-c-100-100-1.jpg" class="img-thumbnail visible-xs picture_mob" />
           <div class="header">
                <h1><%= current_user.gallery.name =%></h1>
                <h5 style="color:#007FBE"><%= current_user.gallery.website %></h5>
                <h4><strong style="color:#007FBE">Location:</strong> <%= current_user.gallery.city %>, <%= current_user.gallery.zip_code %></h4>

                <span><strong style="color:#007FBE">Days Open:</strong> <%= current_user.gallery.days_open %> |
                <strong style="color:#007FBE">Hours:</strong> <%= current_user.gallery.hours_open %></span>

                <h4><strong style="color:black">Genres Accepted:</strong> <strong style="color:#007FBE"><%= current_user.gallery.genres %></strong></h4>
           </div>
        </div>
    </div>

  <div class="row nav">
        <div class="col-md-4"></div>
        <div class="col-md-8 col-xs-12" style="margin: 0px;padding: 0px;">
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-weixin fa-lg"></i> 16</div>
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-heart-o fa-lg"></i> 14</div>
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-thumbs-o-up fa-lg"></i> 26</div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P2Canvache</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
</head>
<body class="container">

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">canvaché</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#"></a>
                </li>
                <li>
                    <a href="#"></a>
                </li>
                <li>
                    <a href="/logout">Done? Leave here!</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<!-- Be sure and add the login / logout info here -->
<%= yield %>

</body>
</html>

app/views/users/home.html.erb
<% if rep %>
    <!-- Page Content -->
    <div id="homePage">
      <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer" style="background-image:url(https://i.imgur.com/sSAjZjK.png)">
            <h1 id="homeHeader">Welcome <%= current_user.name %></h1>
            <% if rep %>
              <p id="homeHeader">Select an Event below to edit or Click to go to your Gallery Profile.</p>
              <p>
              <%= link_to "Gallery Profile", gallery_path(@gallery), class: "btn btn-primary btn-large" %>
              </p>
            <% else %>
              <p>Take a look at what's going on in your area!</p>
            <% end %>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3 id="features">Featured Events</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src= "http://susancorso.com/seedsforsanctuary/wp-content/uploads/2013/04/box_placeholder.jpg" alt="">
                    <div class="caption">
                        <h3><%#= Gallery[0].name %></h3>
                        <p>Basic Event Information Here.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Event Profile</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <!-- OR
            <div class="col-sm-2 col-md-2">
              <img src="http://thetransformedmale.files.wordpress.com/2011/06/bruce-wayne-armani.jpg"
              alt="" class="img-rounded img-responsive" />
            </div>
            <div class="col-sm-4 col-md-4">
              <blockquote>
                <p>Bruce Wayne</p> <small><cite title="Source Title">Gotham, United Kingdom  <i class="glyphicon glyphicon-map-marker"></i></cite></small>
              </blockquote>
              <p> <i class="glyphicon glyphicon-envelope"></i> masterwayne@batman.com
                <br
                /> <i class="glyphicon glyphicon-globe"></i> www.bootsnipp.com
                <br /> <i class="glyphicon glyphicon-gift"></i> January 30, 1974</p>
            </div> -->


            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://susancorso.com/seedsforsanctuary/wp-content/uploads/2013/04/box_placeholder.jpg" alt="">
                    <div class="caption">
                        <h3><%#= Gallery[0].name %></h3>
                        <p>Basic Event Information Here.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Event Profile</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://susancorso.com/seedsforsanctuary/wp-content/uploads/2013/04/box_placeholder.jpg" alt="">
                    <div class="caption">
                        <h3><%#= Gallery[0].name %></h3>
                        <p>Basic Event Information Here.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Event Profile</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://susancorso.com/seedsforsanctuary/wp-content/uploads/2013/04/box_placeholder.jpg" alt="">
                    <div class="caption">
                        <h3><%#= Gallery[0].name %></h3>
                        <p>Basic Event Information Here.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Event Profile</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <% else %>

        <header class="jumbotron hero-spacer" style="background-image:url(https://i.imgur.com/XWraq6u.jpg)">
            <h1 id="homeHeader">Welcome <%= current_user.name %></h1>
              <p id="homeHeader">Select a Gallery or Event below to view details!</p>
              <!--<p><a class="btn btn-primary btn-large" href="/galleries/profile">Gallery Profile</a>
              </p>-->
              <p style="color: #007FBE">Take a look at what's going on in your area!</p>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3 id="features">Featured Galleries</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src= "https://i.imgur.com/60nGKVl.png" alt="">
                    <div class="caption">
                        <h3><%#= Gallery[0].name %></h3>
                        <p>Basic info for that gallery.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Gallery Profile</a> <a href="#" class="btn btn-default">Event Info</a>
                        </p>
                    </div>
                </div>
            </div>


            <!-- OR
            <div class="col-sm-2 col-md-2">
              <img src="http://thetransformedmale.files.wordpress.com/2011/06/bruce-wayne-armani.jpg"
              alt="" class="img-rounded img-responsive" />
            </div>
            <div class="col-sm-4 col-md-4">
              <blockquote>
                <p>Bruce Wayne</p> <small><cite title="Source Title">Gotham, United Kingdom  <i class="glyphicon glyphicon-map-marker"></i></cite></small>
              </blockquote>
              <p> <i class="glyphicon glyphicon-envelope"></i> masterwayne@batman.com
                <br
                /> <i class="glyphicon glyphicon-globe"></i> www.bootsnipp.com
                <br /> <i class="glyphicon glyphicon-gift"></i> January 30, 1974</p>
            </div> -->


            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="https://i.imgur.com/60nGKVl.png" alt="">
                    <div class="caption">
                        <h3><%#= Gallery[0].name %></h3>
                        <p>Basic info for that gallery.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Gallery Profile</a> <a href="#" class="btn btn-default">Event Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="https://i.imgur.com/60nGKVl.png" alt="">
                    <div class="caption">
                        <h3><%#= Gallery[0].name %></h3>
                        <p>Basic info for that gallery.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Gallery Profile</a> <a href="#" class="btn btn-default">Event Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="https://i.imgur.com/60nGKVl.png" alt="">
                    <div class="caption">
                        <h3><%#= Gallery[0].name %></h3>
                        <p>Basic info for that gallery.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Gallery Profile</a> <a href="#" class="btn btn-default">Event Info</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <% end %>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; canvaché 2015</p>
                </div>
            </div>
        </footer>
      </div>
    </div>

app/views/users/new.html.erb
<main id="forms">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Need more info to get you set up!</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <form class="form-horizontal" role="form">
        <fieldset>

          <!-- Form Name -->
          <legend>Sign Up Here</legend>

          <!-- Text input-->
          <div class="form-group">
            <%= f.label :name, class: "col-sm-4 control-label" %>
              <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :email, class: "col-sm-4 control-label" %>
              <div class="col-sm-10">
                <%= f.text_field :email, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :password, class: "col-sm-4 control-label" %>
              <div class="col-sm-10">
                <%= f.password_field :password, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, class: "col-sm-4 control-label" %>
              <div class="col-sm-10">
                <%= f.password_field :password_confirmation, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
            <%= f.label :zip_code, class: "col-sm-4 control-label" %>
              <div class="col-sm-10">
                <%= f.text_field :zip_code, class: "form-control" %>
              </div>
          </div>

          <div class="form-group">
              <div class="col-sm-10">
              </div>
          </div>

          <div class="form-group">
            <%= f.check_box :gallery_rep, class: "col-sm-4 control-label" %>
              <div class="col-sm-10">
                <%= f.label :gallery_rep, "I am a Gallery Representative" %>
              </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="pull-right">
                <%= f.submit "Sign me up!", class: "btn btn-primary" %>
                <!--<button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-primary">Save</button> -->
              </div>
            </div>
          </div>

        </fieldset>
      </form>
    </div><!-- /.col-lg-12 -->
  </div><!-- /.row -->

<% end %>
</main>

app/views/users/profile.html.erb
<h1>Build Your Gallery Profile!</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Need more info to get you set up!</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street_address %>
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code, "Primary Area (Zip-Code)" %>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :website, "Website Link (if applicable)" %>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :genre, "Genres Supported (List)" %>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :days_open, "Days Open for Visitors" %>
    <%= f.text_field :days_open %>
  </div>
  <div class="field">
    <%= f.label :hours_open, "Business Hours" %>
    <%= f.text_field :hours_open %>
  </div>
  <div class="field">
    <%= f.label :img_uri, "Profile Image URI" %>
    <%= f.text_field :img_uri %>
  </div>
  <div class="actions"><%= f.submit "Submit Home Page Profile!" %></div>
<% end %>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <!-- Carousel -->
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
          <div class="item active">
            <img src="http://www.arts.uci.edu/sites/default/files/IMG_5020.JPG" alt="First slide">
                    <!-- Static Header -->
                    <div class="header-text hidden-xs">
                        <div class="col-md-12 text-center">
                            <h2>
                              <span>Welcome to <strong style="color:#F4CD72">canvaché</strong></span>
                            </h2>
                            <br>
                            <h3>
                              <span>Where aspiring artists find their playgrounds.</span>
                            </h3>
                            <br>
                            <div class="">
                                <a class="btn btn-theme btn-sm btn-min-block" href="/sessions/login">Login</a><a class="btn btn-theme btn-sm btn-min-block" href="/users/new">Not Registered? Sign Up!</a></div>
                        </div>
                    </div><!-- /header-text -->
          </div>
          <div class="item">
            <img src="http://camh.org/sites/default/files/130729_CAMH5_DSC7875.jpg" alt="Second slide">
            <!-- Static Header -->
                    <div class="header-text hidden-xs">
                        <div class="col-md-12 text-center">
                            <h2>
                                <span>Welcome to <strong style="color:#F4CD72">canvaché</strong></span>
                            </h2>
                            <br>
                            <h3>
                              <span>Follow your favorites to draw inspiration...</span>
                            </h3>
                            <br>
                            <div class="">
                                <a class="btn btn-theme btn-sm btn-min-block" href="/sessions/login">Login</a><a class="btn btn-theme btn-sm btn-min-block" href="/users/new">Not Registered? Sign Up!</a></div>
                        </div>
                    </div><!-- /header-text -->
          </div>
          <div class="item">
            <img src="https://upload.wikimedia.org/wikipedia/commons/d/d4/New_York_City_at_night_HDR_edit1.jpg" alt="Third slide">
            <!-- Static Header -->
                    <div class="header-text hidden-xs">
                        <div class="col-md-12 text-center">
                            <h2>
                                <span>Welcome to <strong style="color:#F4CD72">canvaché</strong></span>
                            </h2>
                            <br>
                            <h3>
                              <span>...and discover the reach of your full potential.</span>
                            </h3>
                            <br>
                            <div class="">
                                <a class="btn btn-theme btn-sm btn-min-block" href="/sessions/login">Login</a><a class="btn btn-theme btn-sm btn-min-block" href="/users/new">Not Registered? Sign Up!</a></div>
                        </div>
                    </div><!-- /header-text -->
          </div>
      </div>
      <!-- Controls -->
      <!--<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">-->
      <!--    <span class="glyphicon glyphicon-chevron-left"></span>-->
      <!--</a>-->
      <!--<a class="right carousel-control" href="#carousel-example-generic" data-slide="next"-->
      <!--    <span class="glyphicon glyphicon-chevron-right"></span>-->
      <!--</a>-->
    </div><!-- /carousel -->
  </div>
</div>